Update remake

diff --git a/remake b/remake
--- a/remake
+++ b/remake
@@ -1,3 +1,4 @@
+
 #!/bin/bash
 #================================================================================================
 #
@@ -96,7 +97,7 @@ rk3588_kernel=("6.1.y")
 rk35xx_kernel=("6.1.y")
 h6_kernel=("6.6.y")
 specific_6xy=("6.1.y" "6.6.y" "6.12.y")
-specific_5xy=("5.4.y" "5.10.y" "5.15.y")
+specific_5xy=("5.10.y" "5.15.y")
 # Set to automatically use the latest kernel
 auto_kernel="true"
 # Initialize the kernel array
@@ -111,7 +112,7 @@ uboot_meson_sm1=("x96maxplus.bin" "ugoos-x3.bin" "tx3-qz.bin" "tx3-bz.bin" "skyw
 uboot_meson_gxbb=("p201.bin" "s905.bin")
 
 # Set OpenWrt default IP address
-openwrt_ip="192.168.1.1"
+openwrt_ip="10.0.0.138"
 ip_regex="^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
 
 # Initialize the build device
@@ -296,7 +297,7 @@ check_data() {
             >${model_txt}
 
     # Get a list of build devices
-    if [[ "${make_board}" =~ ^(all|top55|after55)$ ]]; then
+    if [[ "${make_board}" =~ ^(all|first55|from55|last20)$ ]]; then
         board_list=":(yes)"
         make_openwrt=($(
             cat ${model_conf} |
@@ -311,13 +312,18 @@ check_data() {
     [[ "${#make_openwrt[@]}" -eq 0 ]] && error_msg "The board is missing, stop making."
 
     # Get the list of boards before the first 55
-    [[ "${make_board}" == "top55" ]] && {
+    [[ "${make_board}" == "first55" ]] && {
         make_openwrt=("${make_openwrt[@]:0:55}")
         board_list=":($(echo ${make_openwrt[@]} | sed -e 's/ /\|/g')):(yes|no)"
     }
     # Get the list of boards after the first 55
-    [[ "${make_board}" == "after55" ]] && {
+    [[ "${make_board}" == "from55" ]] && {
         make_openwrt=("${make_openwrt[@]:55}")
+        board_list=":($(echo ${make_openwrt[@]} | sed -e 's/ /\|/g')):(yes|no)"
+    }
+    # Get the list of boards after the last 20
+    [[ "${make_board}" == "last20" ]] && {
+        make_openwrt=("${make_openwrt[@]: -20}")
         board_list=":($(echo ${make_openwrt[@]} | sed -e 's/ /\|/g')):(yes|no)"
     }
 
@@ -454,7 +460,7 @@ download_depends() {
     git_pull_dir ${uboot_repo} main ${git_path}
     # Move the u-boot files to the storage directory
     mkdir -p ${uboot_path}
-    cp -af --no-preserve=ownership ${git_path}/u-boot/* ${uboot_path}
+    cp -af --no-preserve=ownership ${git_path}/u-boot/. ${uboot_path}
     [[ "${?}" -eq 0 ]] && echo -e "${INFO} OpenWrt: u-boot download completed." || error_msg "OpenWrt: u-boot download failed."
     # Delete temporary files
     rm -rf ${git_path}
@@ -464,7 +470,7 @@ download_depends() {
     git_pull_dir ${firmware_repo} main ${git_path}
     # Move the firmware files to the storage directory
     mkdir -p ${firmware_path}
-    cp -af --no-preserve=ownership ${git_path}/firmware/* ${firmware_path}
+    cp -af --no-preserve=ownership ${git_path}/firmware/. ${firmware_path}
     [[ "${?}" -eq 0 ]] && echo -e "${INFO} OpenWrt: firmware download completed." || error_msg "OpenWrt: firmware download failed."
     # Delete temporary files
     rm -rf ${git_path}
@@ -472,13 +478,13 @@ download_depends() {
     # Download Armbian repository files
     git_path="$(mktemp -d)"
     git_pull_dir ${depends_repo} main ${git_path}
-    # Move the platform files to the storage directory
-    cp -af --no-preserve=ownership ${git_path}/build-armbian/armbian-files/platform-files/* ${platform_files}
-    [[ "${?}" -eq 0 ]] && echo -e "${INFO} OpenWrt: platform-files download completed." || error_msg "OpenWrt: platform-files download failed."
     # Remove the special files in the [ sbin ] directory of the Armbian system
-    rm -rf $(find ${platform_files} -type d -name "sbin")
+    find "${git_path}" -type d -path "*/platform-files/*/rootfs/usr/sbin" -prune -exec rm -rf {} +
+    # Move the platform files to the storage directory
+    cp -af --no-preserve=ownership ${git_path}/build-armbian/armbian-files/platform-files/. ${platform_files}
+    [[ "${?}" -eq 0 ]] && echo -e "${INFO} OpenWrt: platform-files download completed." || error_msg "OpenWrt: platform-files download failed."
     # Move the different files to the storage directory
-    cp -af --no-preserve=ownership ${git_path}/build-armbian/armbian-files/different-files/* ${different_files}
+    cp -af --no-preserve=ownership ${git_path}/build-armbian/armbian-files/different-files/. ${different_files}
     [[ "${?}" -eq 0 ]] && echo -e "${INFO} OpenWrt: different-files download completed." || error_msg "OpenWrt: different-files download failed."
     # Move the balethirq related files to the storage directory
     cp -f --no-preserve=ownership ${git_path}/build-armbian/armbian-files/common-files/usr/sbin/balethirq.pl ${common_files}/usr/sbin
@@ -491,12 +497,12 @@ download_depends() {
     git_path="$(mktemp -d)"
     git_pull_dir ${script_repo} main ${git_path}
     # Move the sbin files to the storage directory
-    cp -af --no-preserve=ownership ${git_path}/luci-app-amlogic/root/usr/sbin/* ${common_files}/usr/sbin
+    cp -af --no-preserve=ownership ${git_path}/luci-app-amlogic/root/usr/sbin/. ${common_files}/usr/sbin
     [[ "${?}" -eq 0 ]] && echo -e "${INFO} luci-app-amlogic: sbin download completed." || error_msg "luci-app-amlogic: sbin download failed."
     chmod +x ${common_files}/usr/sbin/*
     # Move the share files to the storage directory
     mkdir -p ${common_files}/usr/share/amlogic
-    cp -af --no-preserve=ownership ${git_path}/luci-app-amlogic/root/usr/share/amlogic/* ${common_files}/usr/share/amlogic
+    cp -af --no-preserve=ownership ${git_path}/luci-app-amlogic/root/usr/share/amlogic/. ${common_files}/usr/share/amlogic
     [[ "${?}" -eq 0 ]] && echo -e "${INFO} luci-app-amlogic: share download completed." || error_msg "luci-app-amlogic: share download failed."
     chmod +x ${common_files}/usr/share/amlogic/*
     # Delete temporary files
@@ -844,24 +850,24 @@ extract_openwrt() {
     rm -f ${tag_rootfs}/rom/sbin/firstboot
 
     # Copy the common files
-    [[ -d "${common_files}" ]] && cp -af --no-preserve=ownership ${common_files}/* ${tag_rootfs}
+    [[ -d "${common_files}" ]] && cp -af --no-preserve=ownership ${common_files}/. ${tag_rootfs}
 
     # Copy the platform files
     platform_bootfs="${platform_files}/${PLATFORM}/bootfs"
     platform_rootfs="${platform_files}/${PLATFORM}/rootfs"
-    [[ -d "${platform_bootfs}" ]] && cp -rf ${platform_bootfs}/* ${tag_bootfs}
-    [[ -d "${platform_rootfs}" ]] && cp -af --no-preserve=ownership ${platform_rootfs}/* ${tag_rootfs}
+    [[ -d "${platform_bootfs}" ]] && cp -rf ${platform_bootfs}/. ${tag_bootfs}
+    [[ -d "${platform_rootfs}" ]] && cp -af --no-preserve=ownership ${platform_rootfs}/. ${tag_rootfs}
 
     # Copy the different files
     different_bootfs="${different_files}/${board}/bootfs"
     different_rootfs="${different_files}/${board}/rootfs"
-    [[ -d "${different_bootfs}" ]] && cp -rf ${different_bootfs}/* ${tag_bootfs}
-    [[ -d "${different_rootfs}" ]] && cp -af --no-preserve=ownership ${different_rootfs}/* ${tag_rootfs}
+    [[ -d "${different_bootfs}" ]] && cp -rf ${different_bootfs}/. ${tag_bootfs}
+    [[ -d "${different_rootfs}" ]] && cp -af --no-preserve=ownership ${different_rootfs}/. ${tag_rootfs}
 
     # Copy the bootloader files
     [[ -d "${tag_rootfs}/lib/u-boot" ]] || mkdir -p "${tag_rootfs}/lib/u-boot"
     rm -rf ${tag_rootfs}/lib/u-boot/*
-    [[ -d "${bootloader_path}" ]] && cp -af --no-preserve=ownership ${bootloader_path}/* ${tag_rootfs}/lib/u-boot
+    [[ -d "${bootloader_path}" ]] && cp -af --no-preserve=ownership ${bootloader_path}/. ${tag_rootfs}/lib/u-boot
 
     # Copy the Amlogic overload files
     [[ "${PLATFORM}" == "amlogic" ]] && {
@@ -977,7 +983,7 @@ refactor_rootfs() {
     mkdir -p .reserved boot run
 
     # Set default IP address
-    [[ "${openwrt_ip}" != "192.168.1.1" && -f "bin/config_generate" ]] && {
+    [[ "${openwrt_ip}" != "10.0.0.138" && -f "bin/config_generate" ]] && {
         sed -i "/lan) ipad=\${ipaddr:-/s/\${ipaddr:-\"[^\"]*\"}/\${ipaddr:-\"${openwrt_ip}\"}/" bin/config_generate
     }
 
@@ -1011,7 +1017,7 @@ refactor_rootfs() {
     # Add custom startup script
     custom_startup_script="etc/custom_service/start_service.sh"
     [[ -x "${custom_startup_script}" && -f "etc/rc.local" ]] && {
-        sed -i '/^exit 0/i\bash /etc/custom_service/start_service.sh' etc/rc.local
+        sed -i '/^exit 0/i\bash /etc/custom_service/start_service.sh &' etc/rc.local
     }
 
     # Modify the cpu mode to schedutil
